repository:
  description: opinionated scaffolder for JavaScript projects
  homepage: https://npm.im/@travi/javascript-scaffolder
  has_wiki: false
  has_projects: true
  has_downloads: false
  allow_squash_merge: false
  allow_merge_commit: true
  allow_rebase_merge: true
labels:
  - name: bug
    color: ee0701
  - name: duplicate
    color: cccccc
  - name: enhancement
    color: 84b6eb
  - name: help wanted
    color: 128A0C
  - name: invalid
    color: e6e6e6
  - name: question
    color: cc317c
  - name: wontfix
    color: ffffff
  - name: greenkeeper
    color: 00c775
  - name: breaking change
    color: e0fc28
collaborators:
  - username: travi-bot
    permission: push
  - username: trevtrich
    permission: push
