language: node_js
notifications:
  email: false
branches:
  except:
  - "/^v\\d+\\.\\d+\\.\\d+$/"
install:
- npm install
- gem install travis
before_script: npm run greenkeeper:update-lockfile
after_script: npm run greenkeeper:upload-lockfile
after_success: npm run coverage:report
deploy:
  provider: script
  skip_cleanup: true
  script: npx semantic-release
env:
  global:
  - FORCE_COLOR=1
  - NPM_CONFIG_COLOR=always
  - secure: kbPjHjPIcZwbp6o/Cb9tGIO42PVOMLk7H6SyyJQ3oMLodUU5XlwdMYX6Jx4dDNd6YN1ZNg7Kyc0jNIcMIxLg77xZ3xhk1sV43uw/em49EKttMnkg8im+VHsPUqZYdPyJ6y8EV3jG48fRR/Xv7ar5HuatBW4jV2z8z+5Lge2delm3m6MP9FZD/jcKMZ+SBeYMc5i3nPQdk65zRDngyaxX1zKUwF0loDV6A1+pdCGPXLzHOf8zFXIy49UZH4y76IPYChe7UqbYLPUofrjLGgP8ZgCpPo4R9Bll6mbuBn+rxL9AQLvzUJplfh7uluKG4XTXzwmtPzDvKWPXkyXaONp+TlLLfZEv67K9wffz6hG5NzwR7Yl7hFfol6Rfoj/BDBgPNeOsWq+yNdu40nu6nqh0tVdYwu/69PBpuJsZagrQKO2IjbRL7YTkYmV8hKme6Yn5n4MsqpYEQ8cvt81jOBv9LSQJVJYi719wraYKPruC/Atwu0ZPMrc7Jco4/G0WQghhvagqY9WV4G/JcV96Dnj2mdhdSATZoa9zk/JPmrZEXpW02gxZ3UZXANdv6CllmfhV+wPyI8P8UeNIZuMhcveS8VwvauLE7ZmkLQRGyGBaYF5eDMc09Gnz23bSrttEaYWp7KqHNN3MQYGtphes3PZ1mbZSaH0dgMrTdrEl+KfwUqI=
