dist: xenial
language: node_js
notifications:
  email: false
branches:
  except:
  - "/^v\\d+\\.\\d+\\.\\d+$/"
before_install: curl ifconfig.co
before_script: npm ls >/dev/null
after_success: npm run coverage:report
deploy:
  provider: script
  edge: true
  script: npx semantic-release@beta
  on:
    all_branches: true
env:
  global:
  - FORCE_COLOR=1
  - NPM_CONFIG_COLOR=always
